title: yangdm-space
author: yangdm
email: yangdeming0@126.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
lang: zh-Hans # site language (en/ja/zh-Hans/zh-Hant)
color_scheme: github # this specifies color scheme for syntax highlighting
github_username: yangdm
twitter_username: yangdm
instagram_username: yangdm

# Build settings
markdown: kramdown
theme: jekyll-theme-kagami
exclude:
  - Gemfile
  - Gemfile.lock
